# Generated by Django 5.2.1 on 2026-05-21 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('accepted', 'Принят'), ('cooking', 'Готовится'), ('delivering', 'Доставляется'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='new', max_length=20)),
                ('delivery_method', models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')], default='delivery', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card_on_delivery', 'Карта при получении'), ('online_later', 'Онлайн оплата позже')], default='cash', max_length=30)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='users.telegramuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=160)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
